apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  namespace: collector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
        - name: collector
          image: parag/atlan-lily:collector
          ports:
          - containerPort: 8001
          resources:
            requests:
              memory: "500Mi"
              cpu: "0.5"
            limits:
              memory: "500Mi"
              cpu: "0.5"