version: '3.5'
services:
  crdb:
    image: cockroachdb/cockroach:v19.2.2
    container_name: cockroachdb
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"
  postgres:
    image: postgres:14.5
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=atlan
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pubsub:
    image: google/cloud-sdk:320.0.0-emulators
    container_name: pubsub
    command: gcloud --quiet beta emulators pubsub start --project=atlan-lily --host-port=0.0.0.0:8090
    ports:
      - "8090:8090"
volumes:
  postgres_db:
    driver: local

