apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub
  namespace: pubsub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub
  template:
    metadata:
      labels:
        app: pubsub
    spec:
      containers:
        - name: pubsub-emulator
          image: google/cloud-sdk:320.0.0-emulators
          command: [ "gcloud", "--quiet", "beta", "emulators", "pubsub", "start" ]
          args: [ "--project=atlan-lily", "--host-port=0.0.0.0:8080" ]
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"